 
package RightClick;

 
public class MenuPopUp extends javax.swing.JPanel {
 
    public MenuPopUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(82, 59, 53));
        setLayout(new java.awt.GridLayout(0, 1, 15, 5));

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        add(jButton1);

        jButton3.setText("jButton3");
        jButton3.setFocusable(false);
        add(jButton3);

        jButton4.setText("jButton4");
        jButton4.setFocusable(false);
        add(jButton4);

        jButton2.setText("jButton2");
        jButton2.setFocusable(false);
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
